# Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [97]:
import numpy as np
import pandas as pd

In [10]:
Array1=np.array([14,21,52,32,14,52,12,14])
Array2=np.array([21,5,52,14,12,10,2,14])
print(Array1>Array2)
print(Array1>=Array2)
print(Array1<Array2)
print(Array1<=Array2)

[False  True False  True  True  True  True False]
[False  True  True  True  True  True  True  True]
[ True False False False False False False False]
[ True False  True False False False False  True]


# Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [19]:
Array_0=np.zeros(10,int)
Array_1=np.ones(10,int)
Array_5=np.ones(10,int)*5
print(Array_0)
print(Array_1)
print(Array_5)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


# Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [36]:
Array3 = np.array([[12,25,32,45,12],[14,4,24,36,25],[2,41,23,36,54]])

In [57]:
#sum of each row
count_row=0
for i in Array3:
    print("Sum of row {} is : {}".format(count_row,sum(i)))
    count_row+=1

Sum of row 0 is : 126
Sum of row 1 is : 103
Sum of row 2 is : 156


In [66]:
#Some of each column
#count_column=0
for i in range(Array3.shape[1]):
    print("Sum of columm {} is : {}".format(i,sum(Array3[:,i])))

Sum of columm 0 is : 28
Sum of columm 1 is : 70
Sum of columm 2 is : 79
Sum of columm 3 is : 117
Sum of columm 4 is : 91


# Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [96]:
array1=np.array([10,21,45,23,56,41])
array2=np.array([12,20,14,52,36,2])

print("Add : {}".format(np.add(array1,array2)))
print("\n")
print("subtract : {}".format(np.subtract(array1,array2)))
print("\n")
print("multiply : {}".format(np.multiply(array1,array2)))
print("\n")
print("divide : {}".format(np.divide(array1,array2)))

Add : [22 41 59 75 92 43]


subtract : [ -2   1  31 -29  20  39]


multiply : [ 120  420  630 1196 2016   82]


divide : [ 0.83333333  1.05        3.21428571  0.44230769  1.55555556 20.5       ]


# Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [95]:
degree=np.array([45,55,30,60,90,320,180,85,80])

print("sine : {}".format(np.sin(degree)))
print("\n")
print("cosine : {}".format(np.cos(degree)))
print("\n")
print("tangent : {}".format(np.tan(degree)))

sine : [ 0.85090352 -0.99975517 -0.98803162 -0.30481062  0.89399666 -0.42815543
 -0.80115264 -0.17607562 -0.99388865]


cosine : [ 0.52532199  0.02212676  0.15425145 -0.95241298 -0.44807362  0.90370511
 -0.59846007 -0.98437664 -0.11038724]


tangent : [  1.61977519 -45.18308791  -6.4053312    0.32004039  -1.99520041
  -0.47377781   1.33869021   0.17887017   9.00365495]


# Question 6:
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [103]:
DataFrame=pd.DataFrame({"Subject":["Python","Data Structure","Statistics","Machine Learning","Opereting System","Java","Big Data"],
                        "Marks":[29,25,27,26,23,26,28],
                        "Rate":["Excellent","Good","Very Good","Good","Good","Good","Very good"]})

In [104]:
print(DataFrame)

            Subject  Marks       Rate
0            Python     29  Excellent
1    Data Structure     25       Good
2        Statistics     27  Very Good
3  Machine Learning     26       Good
4  Opereting System     23       Good
5              Java     26       Good
6          Big Data     28  Very good


In [108]:
DataFrame.columns

Index(['Subject', 'Marks', 'Rate'], dtype='object')